### ISSUE TITLE
Becoming an Open Source CNA - Node.js ecosystem

### ISSUE THREAD

**Issue by vdeturckheim** [distributedweaknessfiling/DWF-Documentation#10]
The Node.js Security Working group has been discussing about becoming a CNA for the Node.js ecosystem (https://github.com/nodejs/security-wg/issues/97).
It seems that the form is not available yet. What is the best way to move forward here?
We already have a CNA experience for Node.js itself (see https://github.com/nodejs/security-wg/blob/master/processes/cve_management_process.md) and we can easily create and maintain a similar policy for the ecosystem. When we asked about creating a similar CNA, we were redirected here.
The scope of such CNA would fit the definition we have of a package (https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md#definitions): "a package is a module available for use with Node.js and hosted on the npmjs.org repository".

**Comment by philips** [comment]
I think DWF is being folded back into mitre at this point http://cve.mitre.org/news/archives/2019/news.html#March072019_CVE_Program_Root_CNA_to_Assume_DWFs_Open_Source_Product_Coverage_Responsibilities_Beginning_March_7

**Comment by kurtseifried** [comment]
dwf is closing up shop.
