### ISSUE TITLE
Possible enhancements for "is it a vulnerability"

### ISSUE THREAD

**Issue by attritionorg** [distributedweaknessfiling/DWF-Documentation#7]
https://github.com/distributedweaknessfiling/DWF-Documentation/blob/master/CVE-Assignment-is-it-a-vulnerability.md

The last few years have shown a serious uptick in disclosures that are 'not a vulnerability', that may be worth qualifying and expanding on. Often times these are 'self hacks' (e.g. if you type this in a field you can cause a crash or trigger an overflow, for locally installed software) that do not cross privilege boundaries. We also see it frequently on self-XSS, 'vulns' in iOS/android apps related to file uploads that ultimately do something with the same privileges as the attacker, etc. Enumerating some of these could help newer researchers, and some older idiots (e.g. Vulnerability Labs) when it comes to assignments and disclosures.

**Comment by kurtseifried** [comment]
Agreed. First let's let "upstream" (MITRE) quantify the CVE vuln requirements, secondly then let's look at adding to that.

**Comment by kurtseifried** [comment]
suggest we discuss this at the CVE summit, closing for now.
